client_config_backend: settings
client_config:
  client_id: 439446954377-ri9sn7ai3879i2f5uqa3vjopal42e62t.apps.googleusercontent.com
  client_secret: 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
 
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
 
get_refresh_token: True
 
oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install