"""empty message

Revision ID: 363988374c44
Revises: c4ae791405d7
Create Date: 2022-10-08 21:36:48.229596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363988374c44'
down_revision = 'c4ae791405d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
