"""empty message

Revision ID: 3b53470e62e3
Revises: 9e6a1d8f4204
Create Date: 2022-07-24 17:31:03.877907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b53470e62e3'
down_revision = '9e6a1d8f4204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('file_title', sa.Text(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'file_title')
    # ### end Alembic commands ###
