"""empty message

Revision ID: 3d4e695ed3cc
Revises: 9333352ca4e3
Create Date: 2022-09-05 23:44:14.518722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d4e695ed3cc'
down_revision = '9333352ca4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('status', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'status')
    # ### end Alembic commands ###
