"""empty message

Revision ID: 4b3502925a21
Revises: ab19bfd98ebf
Create Date: 2022-08-06 11:42:50.239238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3502925a21'
down_revision = 'ab19bfd98ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('google_driver_id', sa.Text(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'google_driver_id')
    # ### end Alembic commands ###
