"""empty message

Revision ID: 74a7b2db7a0e
Revises: 4b3502925a21
Create Date: 2022-08-08 10:20:34.582410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74a7b2db7a0e'
down_revision = '4b3502925a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('avatar_url', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_url')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
