"""empty message

Revision ID: 8154750f74fe
Revises: 1258f981a346
Create Date: 2022-07-13 00:13:57.570706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8154750f74fe'
down_revision = '1258f981a346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('file', sa.Column('downloads', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'downloads')
    op.drop_column('file', 'views')
    # ### end Alembic commands ###
