"""empty message

Revision ID: 9e6a1d8f4204
Revises: 8154750f74fe
Create Date: 2022-07-13 09:44:00.855237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e6a1d8f4204'
down_revision = '8154750f74fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('pages', sa.Integer(), nullable=False))
    op.alter_column('file', 'views',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('file', 'downloads',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('user', sa.Column('user_id', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_id')
    op.alter_column('file', 'downloads',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('file', 'views',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('file', 'pages')
    # ### end Alembic commands ###
