"""empty message

Revision ID: d2d8615dd472
Revises: 3d4e695ed3cc
Create Date: 2022-10-02 19:04:29.849775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2d8615dd472'
down_revision = '3d4e695ed3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Text(length=50),
               existing_nullable=False)
    op.alter_column('file', 'google_driver_id',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=50),
               existing_nullable=True)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Text(length=50),
               existing_nullable=False)
    op.alter_column('user', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Text(length=50),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(length=255),
               existing_nullable=True)
    op.alter_column('user', 'avatar_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(length=255),
               existing_nullable=False)
    op.alter_column('user', 'source',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Text(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'source',
               existing_type=sa.Text(length=50),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('user', 'avatar_url',
               existing_type=sa.Text(length=255),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.Text(length=255),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('user', 'user_id',
               existing_type=sa.Text(length=50),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.Text(length=50),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('file', 'google_driver_id',
               existing_type=sa.Text(length=50),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
    op.alter_column('file', 'user_id',
               existing_type=sa.Text(length=50),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    # ### end Alembic commands ###
